[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.21"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gamma = "GAMMA7meSFWaBXF25oSUgmGRwaW6sCMFLmBNiMSdbHVT"

[registry]
url = "https://github.com/GooseFX1/gamma"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/gamma"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
