[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build_client]
script = """
cd client
cargo build --release
"""

[tasks.build_program]
script = """
anchor build
"""
[tasks.build_all]
dependencies = ["build_program", "build_client"]

[tasks.install_client]
script = """
cargo install --path client
"""
dependencies = ["build_program", "build_client"]

[tasks.deploy_program]
script = """
cp .keys/gaMmp8CxTCKFbtpoGrcxccDtJJSRyF7hzTkKcuPDbRG.json target/deploy/gamma-keypair.json
anchor deploy
anchor idl upgrade -f target/idl/gamma.json gaMmp8CxTCKFbtpoGrcxccDtJJSRyF7hzTkKcuPDbRG
"""
dependencies = ["build_program"]

[tasks.deploy_all]
dependencies = ["build_all", "install_client", "deploy_program"]
